/*
   Copyright 2008 Olivier Chafik

   Licensed under the Apache License, Version 2.0 (the License);
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an AS IS BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

   This file comes from the Jeneral project (Java Reifiable Generics & Class Templates)

       http://jeneral.googlecode.com/.
*/
package com.ochafik.lang.jeneral.examples;


import java.io.IOException;

import javax.swing.JLabel;

import com.ochafik.lang.jeneral.annotations.ParamConstructor;
import com.ochafik.lang.jeneral.annotations.Property;
import com.ochafik.lang.jeneral.annotations.Template;
import com.ochafik.lang.jeneral.runtime.Array;

// Declare that ElementsBuild is a template.
// It has to be abstract and to implement ElementsBuilder_Template, which is autogenerated on the fly in Eclipse, NetBeans or with the apt tool in Sun's JDK
@Template
public abstract class TextElementsBuilder<T> implements _TextElementsBuilder<T> {
	 
	// Generate getters and setters for the 'arg' property, and append it to all ElementBuilder's factory methods
	@Property(construct = true)
	public String arg;
	
	
	// Declare that T must have a constructor T(String) that throws no checked exception, and that it should be accessible as the method new_T :
	@ParamConstructor
	public abstract T new_T(String arg) throws IOException;
	
	public void fill(Array<T> array) throws IOException {
		for (int i = array.length(); i-- != 0;) {
			array.set(i, new_T(getArg()));
		}
	}
	
	public T buildElement() throws IOException {
		return new_T(getArg());
	}
	
	public Array<T> buildElementsArray(int size) throws IOException {
		Array<T> array = T(size);
		for (int i = size; i-- != 0;) {
			array.set(i, new_T(getArg()));
		}
		int effectiveLength = array.length();
		if (effectiveLength != size)
			throw new RuntimeException("Bad length");
		
		for (int i = size; i-- != 0;) {
			if (array.get(i) == null) {
				throw new RuntimeException("Empty value");
			}
		}
		
		return array;
	}
	
	@ParamConstructor
	public abstract T new_T(T other) throws IOException;
	
	@ParamConstructor
	public abstract T new_T();
	
	@ParamConstructor(returnNeutralValue = true)
	public abstract T neutral_T();
	
	public void test() {
		Array<T> array = T(10);
		Class<?> tArrayClass = array.getClass();
		Class<T> tClass = this.T();
		Class<?> tClass2 = new_T().getClass();
		array.set(0, new_T());
	}
}
